services:
  # Production User App
  prod-app:
    container_name: prod-app
    build:
      context: ..
      dockerfile: ./Docker/Dockerfile.app
      target: app-production
    restart: always
    expose:
      - "80"
    networks:
      - prod-net
      - proxy-network
    profiles:
      - production

  # Production Admin App
  prod-admin:
    container_name: prod-admin
    build:
      context: ..
      dockerfile: ./Docker/Dockerfile.admin
      target: admin-production
    restart: always
    expose:
      - "80"
    networks:
      - prod-net
      - proxy-network
    profiles:
      - production

  # Production Client App (Next.js)
  prod-client:
    container_name: prod-client
    build:
      context: ..
      dockerfile: ./Docker/Dockerfile.client
      target: client-production
    restart: always
    expose:
      - "3000"
    networks:
      - prod-net
      - proxy-network
    profiles:
      - production
  
networks:
  app-net:
    driver: bridge
  prod-net:
    driver: bridge
  proxy-network:
    external: true
